"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['__init__.py']
OPTIONS = {'argv_emulation': True,
 'iconfile': 'favicon.icns',
 'plist': {'CFBundleDevelopmentRegion': 'English',
           'CFBundleDisplayName': 'VTMO Leonhardt',
           'CFBundleDocumentTypes': [{'CFBundleTypeOSTypes': ['****',
                                                              'fold',
                                                              'disk'],
                                      'CFBundleTypeRole': 'Viewer'}],
           'CFBundleExecutable': '__init__',
           'CFBundleIconFile': 'favicon.icns',
           'CFBundleIdentifier': 'org.atomium.vtmo.leonhardt',
           'CFBundleInfoDictionaryVersion': '6.0',
           'CFBundleName': 'VTMO Leonhardt',
           'CFBundlePackageType': 'APPL',
           'CFBundleShortVersionString': '1.0.0',
           'CFBundleVersion': '1.0.0',
           'LSHasLocalizedDisplayName': False,
           'NSAppleScriptEnabled': False,
           'NSMainNibFile': 'MainMenu',
           'NSPrincipalClass': 'NSApplication',
           'PyMainFileNames': ['__boot__'],
           'PyOptions': {'alias': True,
                         'argv_emulation': True,
                         'emulate_shell_environment': False,
                         'no_chdir': False,
                         'prefer_ppc': False,
                         'site_packages': False,
                         'use_faulthandler': False,
                         'use_pythonpath': False,
                         'verbose': False},
           'PyResourcePackages': [],
           'PyRuntimeLocations': ['@executable_path/../Frameworks/Python.framework/Versions/2.7/Python',
                                  '/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/Python'],
           'PythonInfoDict': {'PythonExecutable': '/usr/local/opt/python/bin/python2.7',
                              'PythonLongVersion': '2.7.7 (default, Jun 14 2014, 23:12:13) \n[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)]',
                              'PythonShortVersion': '2.7',
                              'py2app': {'alias': True,
                                         'template': 'app',
                                         'version': '0.8.1'}}}}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'numpy', 'scipy', 'PyQt4'],
)
