# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/manuelleonhardt/Dropbox/Workspaces/pycharm/vtmo-leonhardt/gui/main_window_view.ui'
#
# Created: Thu Jun 19 23:48:06 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1002, 906)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.timeline_widget = QtGui.QWidget(self.centralwidget)
        self.timeline_widget.setObjectName(_fromUtf8("timeline_widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.timeline_widget)
        self.gridLayout_2.setMargin(12)
        self.gridLayout_2.setHorizontalSpacing(8)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.timeline_frame_range_lower = QtGui.QLabel(self.timeline_widget)
        self.timeline_frame_range_lower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeline_frame_range_lower.setObjectName(_fromUtf8("timeline_frame_range_lower"))
        self.gridLayout_2.addWidget(self.timeline_frame_range_lower, 0, 0, 1, 1)
        self.timeline_frame_range_upper = QtGui.QLabel(self.timeline_widget)
        self.timeline_frame_range_upper.setObjectName(_fromUtf8("timeline_frame_range_upper"))
        self.gridLayout_2.addWidget(self.timeline_frame_range_upper, 0, 4, 1, 1)
        self.timeline_frame_range_window_lower_spinbox = QtGui.QSpinBox(self.timeline_widget)
        self.timeline_frame_range_window_lower_spinbox.setObjectName(_fromUtf8("timeline_frame_range_window_lower_spinbox"))
        self.gridLayout_2.addWidget(self.timeline_frame_range_window_lower_spinbox, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(385, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.timeline_frame_index_spinbox = QtGui.QSpinBox(self.timeline_widget)
        self.timeline_frame_index_spinbox.setObjectName(_fromUtf8("timeline_frame_index_spinbox"))
        self.gridLayout_2.addWidget(self.timeline_frame_index_spinbox, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(384, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        self.timeline_frame_range_window_upper_spinbox = QtGui.QSpinBox(self.timeline_widget)
        self.timeline_frame_range_window_upper_spinbox.setObjectName(_fromUtf8("timeline_frame_range_window_upper_spinbox"))
        self.gridLayout_2.addWidget(self.timeline_frame_range_window_upper_spinbox, 1, 4, 1, 1)
        self.timeline_slider = QtGui.QSlider(self.timeline_widget)
        self.timeline_slider.setOrientation(QtCore.Qt.Horizontal)
        self.timeline_slider.setObjectName(_fromUtf8("timeline_slider"))
        self.gridLayout_2.addWidget(self.timeline_slider, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.timeline_widget, 1, 0, 1, 3)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(400, 16777215))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.options_widget = QtGui.QWidget()
        self.options_widget.setEnabled(True)
        self.options_widget.setGeometry(QtCore.QRect(0, 0, 385, 874))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_widget.sizePolicy().hasHeightForWidth())
        self.options_widget.setSizePolicy(sizePolicy)
        self.options_widget.setObjectName(_fromUtf8("options_widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.options_widget)
        self.verticalLayout_3.setSpacing(32)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.viewer_groupbox = QtGui.QGroupBox(self.options_widget)
        self.viewer_groupbox.setObjectName(_fromUtf8("viewer_groupbox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.viewer_groupbox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line_3 = QtGui.QFrame(self.viewer_groupbox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 1, 0, 1, 3)
        self.viewer_exposure_label_2 = QtGui.QLabel(self.viewer_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_exposure_label_2.sizePolicy().hasHeightForWidth())
        self.viewer_exposure_label_2.setSizePolicy(sizePolicy)
        self.viewer_exposure_label_2.setMinimumSize(QtCore.QSize(105, 0))
        self.viewer_exposure_label_2.setMaximumSize(QtCore.QSize(105, 16777215))
        self.viewer_exposure_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.viewer_exposure_label_2.setObjectName(_fromUtf8("viewer_exposure_label_2"))
        self.gridLayout_6.addWidget(self.viewer_exposure_label_2, 2, 0, 1, 1)
        self.viewer_exposure_label = QtGui.QLabel(self.viewer_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_exposure_label.sizePolicy().hasHeightForWidth())
        self.viewer_exposure_label.setSizePolicy(sizePolicy)
        self.viewer_exposure_label.setMinimumSize(QtCore.QSize(105, 0))
        self.viewer_exposure_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.viewer_exposure_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.viewer_exposure_label.setObjectName(_fromUtf8("viewer_exposure_label"))
        self.gridLayout_6.addWidget(self.viewer_exposure_label, 0, 0, 1, 1)
        self.viewer_exposure_slider = QDoubleSlider(self.viewer_groupbox)
        self.viewer_exposure_slider.setMinimum(-10)
        self.viewer_exposure_slider.setMaximum(10)
        self.viewer_exposure_slider.setSingleStep(1)
        self.viewer_exposure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.viewer_exposure_slider.setObjectName(_fromUtf8("viewer_exposure_slider"))
        self.gridLayout_6.addWidget(self.viewer_exposure_slider, 0, 1, 1, 1)
        self.viewer_exposure_spinbox = QtGui.QDoubleSpinBox(self.viewer_groupbox)
        self.viewer_exposure_spinbox.setMinimum(-10.0)
        self.viewer_exposure_spinbox.setMaximum(10.0)
        self.viewer_exposure_spinbox.setSingleStep(0.1)
        self.viewer_exposure_spinbox.setObjectName(_fromUtf8("viewer_exposure_spinbox"))
        self.gridLayout_6.addWidget(self.viewer_exposure_spinbox, 0, 2, 1, 1)
        self.viewer_exposure_label_5 = QtGui.QLabel(self.viewer_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_exposure_label_5.sizePolicy().hasHeightForWidth())
        self.viewer_exposure_label_5.setSizePolicy(sizePolicy)
        self.viewer_exposure_label_5.setMinimumSize(QtCore.QSize(105, 0))
        self.viewer_exposure_label_5.setMaximumSize(QtCore.QSize(105, 16777215))
        self.viewer_exposure_label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.viewer_exposure_label_5.setObjectName(_fromUtf8("viewer_exposure_label_5"))
        self.gridLayout_6.addWidget(self.viewer_exposure_label_5, 3, 0, 1, 1)
        self.viewer_exposure_label_3 = QtGui.QLabel(self.viewer_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_exposure_label_3.sizePolicy().hasHeightForWidth())
        self.viewer_exposure_label_3.setSizePolicy(sizePolicy)
        self.viewer_exposure_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.viewer_exposure_label_3.setObjectName(_fromUtf8("viewer_exposure_label_3"))
        self.gridLayout_6.addWidget(self.viewer_exposure_label_3, 2, 1, 1, 2)
        self.viewer_exposure_label_4 = QtGui.QLabel(self.viewer_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_exposure_label_4.sizePolicy().hasHeightForWidth())
        self.viewer_exposure_label_4.setSizePolicy(sizePolicy)
        self.viewer_exposure_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.viewer_exposure_label_4.setObjectName(_fromUtf8("viewer_exposure_label_4"))
        self.gridLayout_6.addWidget(self.viewer_exposure_label_4, 3, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.viewer_groupbox)
        self.preparing_groupbox = QtGui.QGroupBox(self.options_widget)
        self.preparing_groupbox.setObjectName(_fromUtf8("preparing_groupbox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.preparing_groupbox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sequence_exposure_offset_label = QtGui.QLabel(self.preparing_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_exposure_offset_label.sizePolicy().hasHeightForWidth())
        self.sequence_exposure_offset_label.setSizePolicy(sizePolicy)
        self.sequence_exposure_offset_label.setMinimumSize(QtCore.QSize(105, 0))
        self.sequence_exposure_offset_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.sequence_exposure_offset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sequence_exposure_offset_label.setObjectName(_fromUtf8("sequence_exposure_offset_label"))
        self.gridLayout_5.addWidget(self.sequence_exposure_offset_label, 0, 0, 1, 1)
        self.sequence_exposure_offset_slider = QDoubleSlider(self.preparing_groupbox)
        self.sequence_exposure_offset_slider.setMinimum(-10)
        self.sequence_exposure_offset_slider.setMaximum(10)
        self.sequence_exposure_offset_slider.setSingleStep(1)
        self.sequence_exposure_offset_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sequence_exposure_offset_slider.setObjectName(_fromUtf8("sequence_exposure_offset_slider"))
        self.gridLayout_5.addWidget(self.sequence_exposure_offset_slider, 0, 1, 1, 1)
        self.sequence_exposure_offset_spinbox = QtGui.QDoubleSpinBox(self.preparing_groupbox)
        self.sequence_exposure_offset_spinbox.setMinimum(-10.0)
        self.sequence_exposure_offset_spinbox.setMaximum(10.0)
        self.sequence_exposure_offset_spinbox.setSingleStep(0.1)
        self.sequence_exposure_offset_spinbox.setObjectName(_fromUtf8("sequence_exposure_offset_spinbox"))
        self.gridLayout_5.addWidget(self.sequence_exposure_offset_spinbox, 0, 2, 1, 1)
        self.temporal_quantile_uppper_label = QtGui.QLabel(self.preparing_groupbox)
        self.temporal_quantile_uppper_label.setMinimumSize(QtCore.QSize(105, 0))
        self.temporal_quantile_uppper_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.temporal_quantile_uppper_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temporal_quantile_uppper_label.setObjectName(_fromUtf8("temporal_quantile_uppper_label"))
        self.gridLayout_5.addWidget(self.temporal_quantile_uppper_label, 3, 0, 1, 1)
        self.temporal_quantile_lower_spinbox = QtGui.QDoubleSpinBox(self.preparing_groupbox)
        self.temporal_quantile_lower_spinbox.setMinimum(0.0)
        self.temporal_quantile_lower_spinbox.setMaximum(1.0)
        self.temporal_quantile_lower_spinbox.setSingleStep(0.01)
        self.temporal_quantile_lower_spinbox.setObjectName(_fromUtf8("temporal_quantile_lower_spinbox"))
        self.gridLayout_5.addWidget(self.temporal_quantile_lower_spinbox, 2, 2, 1, 1)
        self.temporal_quantile_lower_slider = QDoubleSlider(self.preparing_groupbox)
        self.temporal_quantile_lower_slider.setMinimum(0)
        self.temporal_quantile_lower_slider.setMaximum(1)
        self.temporal_quantile_lower_slider.setProperty("value", 0)
        self.temporal_quantile_lower_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temporal_quantile_lower_slider.setObjectName(_fromUtf8("temporal_quantile_lower_slider"))
        self.gridLayout_5.addWidget(self.temporal_quantile_lower_slider, 2, 1, 1, 1)
        self.temporal_quantile_lower_label = QtGui.QLabel(self.preparing_groupbox)
        self.temporal_quantile_lower_label.setMinimumSize(QtCore.QSize(105, 0))
        self.temporal_quantile_lower_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.temporal_quantile_lower_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temporal_quantile_lower_label.setObjectName(_fromUtf8("temporal_quantile_lower_label"))
        self.gridLayout_5.addWidget(self.temporal_quantile_lower_label, 2, 0, 1, 1)
        self.temporal_quantile_upper_slider = QDoubleSlider(self.preparing_groupbox)
        self.temporal_quantile_upper_slider.setMinimum(0)
        self.temporal_quantile_upper_slider.setMaximum(1)
        self.temporal_quantile_upper_slider.setProperty("value", 1)
        self.temporal_quantile_upper_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temporal_quantile_upper_slider.setObjectName(_fromUtf8("temporal_quantile_upper_slider"))
        self.gridLayout_5.addWidget(self.temporal_quantile_upper_slider, 3, 1, 1, 1)
        self.temporal_quantile_upper_spinbox = QtGui.QDoubleSpinBox(self.preparing_groupbox)
        self.temporal_quantile_upper_spinbox.setMinimum(0.0)
        self.temporal_quantile_upper_spinbox.setMaximum(1.0)
        self.temporal_quantile_upper_spinbox.setSingleStep(0.01)
        self.temporal_quantile_upper_spinbox.setProperty("value", 1.0)
        self.temporal_quantile_upper_spinbox.setObjectName(_fromUtf8("temporal_quantile_upper_spinbox"))
        self.gridLayout_5.addWidget(self.temporal_quantile_upper_spinbox, 3, 2, 1, 1)
        self.temporal_prepare_pushbutton = QtGui.QPushButton(self.preparing_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temporal_prepare_pushbutton.sizePolicy().hasHeightForWidth())
        self.temporal_prepare_pushbutton.setSizePolicy(sizePolicy)
        self.temporal_prepare_pushbutton.setObjectName(_fromUtf8("temporal_prepare_pushbutton"))
        self.gridLayout_5.addWidget(self.temporal_prepare_pushbutton, 4, 0, 1, 3)
        self.line_2 = QtGui.QFrame(self.preparing_groupbox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_5.addWidget(self.line_2, 1, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.preparing_groupbox)
        self.tonemapper_groupbox = QtGui.QGroupBox(self.options_widget)
        self.tonemapper_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tonemapper_groupbox.setObjectName(_fromUtf8("tonemapper_groupbox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tonemapper_groupbox)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.detaildrawback_lambda_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.detaildrawback_lambda_spinbox.setMinimum(0.0)
        self.detaildrawback_lambda_spinbox.setMaximum(10.0)
        self.detaildrawback_lambda_spinbox.setSingleStep(0.1)
        self.detaildrawback_lambda_spinbox.setObjectName(_fromUtf8("detaildrawback_lambda_spinbox"))
        self.gridLayout_3.addWidget(self.detaildrawback_lambda_spinbox, 14, 2, 1, 1)
        self.detaildrawback_detail_highlight_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.detaildrawback_detail_highlight_slider.setMinimum(0)
        self.detaildrawback_detail_highlight_slider.setMaximum(1)
        self.detaildrawback_detail_highlight_slider.setProperty("value", 0)
        self.detaildrawback_detail_highlight_slider.setOrientation(QtCore.Qt.Horizontal)
        self.detaildrawback_detail_highlight_slider.setObjectName(_fromUtf8("detaildrawback_detail_highlight_slider"))
        self.gridLayout_3.addWidget(self.detaildrawback_detail_highlight_slider, 12, 1, 1, 1)
        self.detaildrawback_lambda_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.detaildrawback_lambda_slider.setMinimum(0)
        self.detaildrawback_lambda_slider.setMaximum(10)
        self.detaildrawback_lambda_slider.setProperty("value", 0)
        self.detaildrawback_lambda_slider.setOrientation(QtCore.Qt.Horizontal)
        self.detaildrawback_lambda_slider.setObjectName(_fromUtf8("detaildrawback_lambda_slider"))
        self.gridLayout_3.addWidget(self.detaildrawback_lambda_slider, 14, 1, 1, 1)
        self.detaildrawback_detail_drawback_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.detaildrawback_detail_drawback_slider.setMinimum(0)
        self.detaildrawback_detail_drawback_slider.setMaximum(2)
        self.detaildrawback_detail_drawback_slider.setProperty("value", 0)
        self.detaildrawback_detail_drawback_slider.setOrientation(QtCore.Qt.Horizontal)
        self.detaildrawback_detail_drawback_slider.setObjectName(_fromUtf8("detaildrawback_detail_drawback_slider"))
        self.gridLayout_3.addWidget(self.detaildrawback_detail_drawback_slider, 11, 1, 1, 1)
        self.detaildrawback_detail_drawback_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.detaildrawback_detail_drawback_spinbox.setMinimum(0.0)
        self.detaildrawback_detail_drawback_spinbox.setMaximum(2.0)
        self.detaildrawback_detail_drawback_spinbox.setSingleStep(0.1)
        self.detaildrawback_detail_drawback_spinbox.setProperty("value", 0.0)
        self.detaildrawback_detail_drawback_spinbox.setObjectName(_fromUtf8("detaildrawback_detail_drawback_spinbox"))
        self.gridLayout_3.addWidget(self.detaildrawback_detail_drawback_spinbox, 11, 2, 1, 1)
        self.detaildrawback_lambda_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.detaildrawback_lambda_label.setMinimumSize(QtCore.QSize(105, 0))
        self.detaildrawback_lambda_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.detaildrawback_lambda_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detaildrawback_lambda_label.setObjectName(_fromUtf8("detaildrawback_lambda_label"))
        self.gridLayout_3.addWidget(self.detaildrawback_lambda_label, 14, 0, 1, 1)
        self.detaildrawback_alpha_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.detaildrawback_alpha_slider.setMinimum(0)
        self.detaildrawback_alpha_slider.setMaximum(10)
        self.detaildrawback_alpha_slider.setProperty("value", 0)
        self.detaildrawback_alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.detaildrawback_alpha_slider.setObjectName(_fromUtf8("detaildrawback_alpha_slider"))
        self.gridLayout_3.addWidget(self.detaildrawback_alpha_slider, 13, 1, 1, 1)
        self.detaildrawback_alpha_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.detaildrawback_alpha_spinbox.setMinimum(0.0)
        self.detaildrawback_alpha_spinbox.setMaximum(10.0)
        self.detaildrawback_alpha_spinbox.setSingleStep(0.1)
        self.detaildrawback_alpha_spinbox.setObjectName(_fromUtf8("detaildrawback_alpha_spinbox"))
        self.gridLayout_3.addWidget(self.detaildrawback_alpha_spinbox, 13, 2, 1, 1)
        self.tonemapper_gamma_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.tonemapper_gamma_spinbox.setMinimum(0.01)
        self.tonemapper_gamma_spinbox.setMaximum(10.0)
        self.tonemapper_gamma_spinbox.setSingleStep(0.1)
        self.tonemapper_gamma_spinbox.setProperty("value", 1.0)
        self.tonemapper_gamma_spinbox.setObjectName(_fromUtf8("tonemapper_gamma_spinbox"))
        self.gridLayout_3.addWidget(self.tonemapper_gamma_spinbox, 8, 2, 1, 1)
        self.tonemapper_gamma_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.tonemapper_gamma_slider.setMinimum(0)
        self.tonemapper_gamma_slider.setMaximum(10)
        self.tonemapper_gamma_slider.setProperty("value", 0)
        self.tonemapper_gamma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tonemapper_gamma_slider.setObjectName(_fromUtf8("tonemapper_gamma_slider"))
        self.gridLayout_3.addWidget(self.tonemapper_gamma_slider, 8, 1, 1, 1)
        self.tonemapper_brightness_offset_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.tonemapper_brightness_offset_slider.setMinimum(-10)
        self.tonemapper_brightness_offset_slider.setMaximum(10)
        self.tonemapper_brightness_offset_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tonemapper_brightness_offset_slider.setObjectName(_fromUtf8("tonemapper_brightness_offset_slider"))
        self.gridLayout_3.addWidget(self.tonemapper_brightness_offset_slider, 3, 1, 1, 1)
        self.tonemapper_contrast_slider = QDoubleSlider(self.tonemapper_groupbox)
        self.tonemapper_contrast_slider.setMinimum(0)
        self.tonemapper_contrast_slider.setMaximum(10)
        self.tonemapper_contrast_slider.setProperty("value", 0)
        self.tonemapper_contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tonemapper_contrast_slider.setObjectName(_fromUtf8("tonemapper_contrast_slider"))
        self.gridLayout_3.addWidget(self.tonemapper_contrast_slider, 7, 1, 1, 1)
        self.tonemapper_contrast_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.tonemapper_contrast_spinbox.setMinimum(0.0)
        self.tonemapper_contrast_spinbox.setMaximum(10.0)
        self.tonemapper_contrast_spinbox.setSingleStep(0.1)
        self.tonemapper_contrast_spinbox.setProperty("value", 0.0)
        self.tonemapper_contrast_spinbox.setObjectName(_fromUtf8("tonemapper_contrast_spinbox"))
        self.gridLayout_3.addWidget(self.tonemapper_contrast_spinbox, 7, 2, 1, 1)
        self.tonemapper_contrast_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.tonemapper_contrast_label.setMinimumSize(QtCore.QSize(105, 0))
        self.tonemapper_contrast_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.tonemapper_contrast_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tonemapper_contrast_label.setObjectName(_fromUtf8("tonemapper_contrast_label"))
        self.gridLayout_3.addWidget(self.tonemapper_contrast_label, 7, 0, 1, 1)
        self.tonemapper_brightness_offset_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.tonemapper_brightness_offset_spinbox.setMinimum(-10.0)
        self.tonemapper_brightness_offset_spinbox.setMaximum(10.0)
        self.tonemapper_brightness_offset_spinbox.setSingleStep(0.1)
        self.tonemapper_brightness_offset_spinbox.setObjectName(_fromUtf8("tonemapper_brightness_offset_spinbox"))
        self.gridLayout_3.addWidget(self.tonemapper_brightness_offset_spinbox, 3, 2, 1, 1)
        self.tonemapper_brightness_offset_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.tonemapper_brightness_offset_label.setMinimumSize(QtCore.QSize(105, 0))
        self.tonemapper_brightness_offset_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.tonemapper_brightness_offset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tonemapper_brightness_offset_label.setObjectName(_fromUtf8("tonemapper_brightness_offset_label"))
        self.gridLayout_3.addWidget(self.tonemapper_brightness_offset_label, 3, 0, 1, 1)
        self.tonemapper_gamma_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.tonemapper_gamma_label.setMinimumSize(QtCore.QSize(105, 0))
        self.tonemapper_gamma_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.tonemapper_gamma_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tonemapper_gamma_label.setObjectName(_fromUtf8("tonemapper_gamma_label"))
        self.gridLayout_3.addWidget(self.tonemapper_gamma_label, 8, 0, 1, 1)
        self.detaildrawback_detail_drawback_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.detaildrawback_detail_drawback_label.setMinimumSize(QtCore.QSize(105, 0))
        self.detaildrawback_detail_drawback_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.detaildrawback_detail_drawback_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detaildrawback_detail_drawback_label.setObjectName(_fromUtf8("detaildrawback_detail_drawback_label"))
        self.gridLayout_3.addWidget(self.detaildrawback_detail_drawback_label, 11, 0, 1, 1)
        self.detaildrawback_drawback_details_checkbox = QtGui.QCheckBox(self.tonemapper_groupbox)
        self.detaildrawback_drawback_details_checkbox.setObjectName(_fromUtf8("detaildrawback_drawback_details_checkbox"))
        self.gridLayout_3.addWidget(self.detaildrawback_drawback_details_checkbox, 10, 0, 1, 3)
        self.detaildrawback_detail_highlight_spinbox = QtGui.QDoubleSpinBox(self.tonemapper_groupbox)
        self.detaildrawback_detail_highlight_spinbox.setMinimum(0.0)
        self.detaildrawback_detail_highlight_spinbox.setMaximum(1.0)
        self.detaildrawback_detail_highlight_spinbox.setSingleStep(0.01)
        self.detaildrawback_detail_highlight_spinbox.setObjectName(_fromUtf8("detaildrawback_detail_highlight_spinbox"))
        self.gridLayout_3.addWidget(self.detaildrawback_detail_highlight_spinbox, 12, 2, 1, 1)
        self.detaildrawback_detail_highlight_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.detaildrawback_detail_highlight_label.setMinimumSize(QtCore.QSize(105, 0))
        self.detaildrawback_detail_highlight_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.detaildrawback_detail_highlight_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detaildrawback_detail_highlight_label.setObjectName(_fromUtf8("detaildrawback_detail_highlight_label"))
        self.gridLayout_3.addWidget(self.detaildrawback_detail_highlight_label, 12, 0, 1, 1)
        self.tonemapper_preview_checkbox = QtGui.QCheckBox(self.tonemapper_groupbox)
        self.tonemapper_preview_checkbox.setObjectName(_fromUtf8("tonemapper_preview_checkbox"))
        self.gridLayout_3.addWidget(self.tonemapper_preview_checkbox, 0, 0, 1, 3)
        self.line = QtGui.QFrame(self.tonemapper_groupbox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 9, 0, 1, 3)
        self.detaildrawback_alpha_label = QtGui.QLabel(self.tonemapper_groupbox)
        self.detaildrawback_alpha_label.setMinimumSize(QtCore.QSize(105, 0))
        self.detaildrawback_alpha_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.detaildrawback_alpha_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detaildrawback_alpha_label.setObjectName(_fromUtf8("detaildrawback_alpha_label"))
        self.gridLayout_3.addWidget(self.detaildrawback_alpha_label, 13, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.tonemapper_groupbox)
        self.temporal_groupbox_2 = QtGui.QGroupBox(self.options_widget)
        self.temporal_groupbox_2.setObjectName(_fromUtf8("temporal_groupbox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.temporal_groupbox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.temporal_lambda_slider = QDoubleSlider(self.temporal_groupbox_2)
        self.temporal_lambda_slider.setMinimum(0)
        self.temporal_lambda_slider.setMaximum(10)
        self.temporal_lambda_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temporal_lambda_slider.setObjectName(_fromUtf8("temporal_lambda_slider"))
        self.gridLayout_7.addWidget(self.temporal_lambda_slider, 2, 1, 1, 1)
        self.temporal_alpha_label = QtGui.QLabel(self.temporal_groupbox_2)
        self.temporal_alpha_label.setMinimumSize(QtCore.QSize(105, 0))
        self.temporal_alpha_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.temporal_alpha_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temporal_alpha_label.setObjectName(_fromUtf8("temporal_alpha_label"))
        self.gridLayout_7.addWidget(self.temporal_alpha_label, 1, 0, 1, 1)
        self.temporal_alpha_spinbox = QtGui.QDoubleSpinBox(self.temporal_groupbox_2)
        self.temporal_alpha_spinbox.setMinimum(0.0)
        self.temporal_alpha_spinbox.setMaximum(10.0)
        self.temporal_alpha_spinbox.setSingleStep(0.1)
        self.temporal_alpha_spinbox.setObjectName(_fromUtf8("temporal_alpha_spinbox"))
        self.gridLayout_7.addWidget(self.temporal_alpha_spinbox, 1, 2, 1, 1)
        self.temporal_lambda_label = QtGui.QLabel(self.temporal_groupbox_2)
        self.temporal_lambda_label.setMinimumSize(QtCore.QSize(105, 0))
        self.temporal_lambda_label.setMaximumSize(QtCore.QSize(105, 16777215))
        self.temporal_lambda_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temporal_lambda_label.setObjectName(_fromUtf8("temporal_lambda_label"))
        self.gridLayout_7.addWidget(self.temporal_lambda_label, 2, 0, 1, 1)
        self.temporal_alpha_slider = QDoubleSlider(self.temporal_groupbox_2)
        self.temporal_alpha_slider.setMinimum(0)
        self.temporal_alpha_slider.setMaximum(10)
        self.temporal_alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temporal_alpha_slider.setObjectName(_fromUtf8("temporal_alpha_slider"))
        self.gridLayout_7.addWidget(self.temporal_alpha_slider, 1, 1, 1, 1)
        self.temporal_lambda_spinbox = QtGui.QDoubleSpinBox(self.temporal_groupbox_2)
        self.temporal_lambda_spinbox.setMinimum(0.0)
        self.temporal_lambda_spinbox.setMaximum(10.0)
        self.temporal_lambda_spinbox.setSingleStep(0.1)
        self.temporal_lambda_spinbox.setObjectName(_fromUtf8("temporal_lambda_spinbox"))
        self.gridLayout_7.addWidget(self.temporal_lambda_spinbox, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.temporal_groupbox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.scrollArea.setWidget(self.options_widget)
        self.gridLayout.addWidget(self.scrollArea, 0, 2, 1, 1)
        self.graphics_view = GraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view.sizePolicy().hasHeightForWidth())
        self.graphics_view.setSizePolicy(sizePolicy)
        self.graphics_view.setSizeIncrement(QtCore.QSize(0, 0))
        self.graphics_view.setStyleSheet(_fromUtf8(""))
        self.graphics_view.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphics_view.setFrameShadow(QtGui.QFrame.Plain)
        self.graphics_view.setLineWidth(0)
        self.graphics_view.setObjectName(_fromUtf8("graphics_view"))
        self.gridLayout.addWidget(self.graphics_view, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        MainWindow.setMenuBar(self.menubar)
        self.action_new = QtGui.QAction(MainWindow)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_render = QtGui.QAction(MainWindow)
        self.action_render.setObjectName(_fromUtf8("action_render"))
        self.action_save_as = QtGui.QAction(MainWindow)
        self.action_save_as.setObjectName(_fromUtf8("action_save_as"))
        self.action_close = QtGui.QAction(MainWindow)
        self.action_close.setObjectName(_fromUtf8("action_close"))
        self.action_export = QtGui.QAction(MainWindow)
        self.action_export.setObjectName(_fromUtf8("action_export"))
        self.menu_file.addAction(self.action_new)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_export)
        self.menu_file.addAction(self.action_render)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_close)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.viewer_exposure_spinbox, self.sequence_exposure_offset_spinbox)
        MainWindow.setTabOrder(self.sequence_exposure_offset_spinbox, self.temporal_quantile_lower_spinbox)
        MainWindow.setTabOrder(self.temporal_quantile_lower_spinbox, self.temporal_quantile_upper_spinbox)
        MainWindow.setTabOrder(self.temporal_quantile_upper_spinbox, self.temporal_prepare_pushbutton)
        MainWindow.setTabOrder(self.temporal_prepare_pushbutton, self.tonemapper_preview_checkbox)
        MainWindow.setTabOrder(self.tonemapper_preview_checkbox, self.tonemapper_brightness_offset_spinbox)
        MainWindow.setTabOrder(self.tonemapper_brightness_offset_spinbox, self.tonemapper_contrast_spinbox)
        MainWindow.setTabOrder(self.tonemapper_contrast_spinbox, self.tonemapper_gamma_spinbox)
        MainWindow.setTabOrder(self.tonemapper_gamma_spinbox, self.detaildrawback_drawback_details_checkbox)
        MainWindow.setTabOrder(self.detaildrawback_drawback_details_checkbox, self.detaildrawback_detail_drawback_spinbox)
        MainWindow.setTabOrder(self.detaildrawback_detail_drawback_spinbox, self.detaildrawback_detail_highlight_spinbox)
        MainWindow.setTabOrder(self.detaildrawback_detail_highlight_spinbox, self.detaildrawback_alpha_spinbox)
        MainWindow.setTabOrder(self.detaildrawback_alpha_spinbox, self.detaildrawback_lambda_spinbox)
        MainWindow.setTabOrder(self.detaildrawback_lambda_spinbox, self.temporal_alpha_spinbox)
        MainWindow.setTabOrder(self.temporal_alpha_spinbox, self.temporal_lambda_spinbox)
        MainWindow.setTabOrder(self.temporal_lambda_spinbox, self.timeline_frame_range_window_lower_spinbox)
        MainWindow.setTabOrder(self.timeline_frame_range_window_lower_spinbox, self.timeline_frame_index_spinbox)
        MainWindow.setTabOrder(self.timeline_frame_index_spinbox, self.timeline_frame_range_window_upper_spinbox)
        MainWindow.setTabOrder(self.timeline_frame_range_window_upper_spinbox, self.viewer_exposure_slider)
        MainWindow.setTabOrder(self.viewer_exposure_slider, self.sequence_exposure_offset_slider)
        MainWindow.setTabOrder(self.sequence_exposure_offset_slider, self.temporal_quantile_lower_slider)
        MainWindow.setTabOrder(self.temporal_quantile_lower_slider, self.temporal_quantile_upper_slider)
        MainWindow.setTabOrder(self.temporal_quantile_upper_slider, self.tonemapper_brightness_offset_slider)
        MainWindow.setTabOrder(self.tonemapper_brightness_offset_slider, self.tonemapper_contrast_slider)
        MainWindow.setTabOrder(self.tonemapper_contrast_slider, self.tonemapper_gamma_slider)
        MainWindow.setTabOrder(self.tonemapper_gamma_slider, self.detaildrawback_detail_drawback_slider)
        MainWindow.setTabOrder(self.detaildrawback_detail_drawback_slider, self.detaildrawback_detail_highlight_slider)
        MainWindow.setTabOrder(self.detaildrawback_detail_highlight_slider, self.detaildrawback_alpha_slider)
        MainWindow.setTabOrder(self.detaildrawback_alpha_slider, self.detaildrawback_lambda_slider)
        MainWindow.setTabOrder(self.detaildrawback_lambda_slider, self.temporal_alpha_slider)
        MainWindow.setTabOrder(self.temporal_alpha_slider, self.temporal_lambda_slider)
        MainWindow.setTabOrder(self.temporal_lambda_slider, self.timeline_slider)
        MainWindow.setTabOrder(self.timeline_slider, self.scrollArea)

    def retranslateUi(self, MainWindow):
        self.timeline_frame_range_lower.setText(_translate("MainWindow", "0", None))
        self.timeline_frame_range_upper.setText(_translate("MainWindow", "0", None))
        self.viewer_groupbox.setTitle(_translate("MainWindow", "Viewer", None))
        self.viewer_exposure_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">IDT</span></p></body></html>", None))
        self.viewer_exposure_label.setText(_translate("MainWindow", "Exposure", None))
        self.viewer_exposure_label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">ODT</span></p></body></html>", None))
        self.viewer_exposure_label_3.setText(_translate("MainWindow", "<html><head/><body><p style=\" font-size:10pt;\">None (assuming sRGB — D65 —linear)</p></body></html>", None))
        self.viewer_exposure_label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">sRGB — D65 — Gamma 2.2</span></p></body></html>", None))
        self.preparing_groupbox.setTitle(_translate("MainWindow", "Preparing", None))
        self.sequence_exposure_offset_label.setText(_translate("MainWindow", "Exposure Offset", None))
        self.temporal_quantile_uppper_label.setText(_translate("MainWindow", "Quantile Upper", None))
        self.temporal_quantile_lower_label.setText(_translate("MainWindow", "Quantile Lower", None))
        self.temporal_prepare_pushbutton.setText(_translate("MainWindow", "Prepare", None))
        self.tonemapper_groupbox.setTitle(_translate("MainWindow", "Tonemapper", None))
        self.detaildrawback_lambda_label.setText(_translate("MainWindow", "Lambda", None))
        self.tonemapper_contrast_label.setText(_translate("MainWindow", "Contrast", None))
        self.tonemapper_brightness_offset_label.setText(_translate("MainWindow", "Brightness", None))
        self.tonemapper_gamma_label.setText(_translate("MainWindow", "Gamma", None))
        self.detaildrawback_detail_drawback_label.setText(_translate("MainWindow", "Detail Drawback", None))
        self.detaildrawback_drawback_details_checkbox.setText(_translate("MainWindow", "Drawback Details", None))
        self.detaildrawback_detail_highlight_label.setText(_translate("MainWindow", "Detail Highlight", None))
        self.tonemapper_preview_checkbox.setText(_translate("MainWindow", "Preview", None))
        self.detaildrawback_alpha_label.setText(_translate("MainWindow", "Alpha", None))
        self.temporal_groupbox_2.setTitle(_translate("MainWindow", "Temporal", None))
        self.temporal_alpha_label.setText(_translate("MainWindow", "Alpha", None))
        self.temporal_lambda_label.setText(_translate("MainWindow", "Lambda", None))
        self.menu_file.setTitle(_translate("MainWindow", "File", None))
        self.action_new.setText(_translate("MainWindow", "New Session...", None))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.action_open.setText(_translate("MainWindow", "Open...", None))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_save.setText(_translate("MainWindow", "Save", None))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_render.setText(_translate("MainWindow", "Render...", None))
        self.action_save_as.setText(_translate("MainWindow", "Save As...", None))
        self.action_close.setText(_translate("MainWindow", "Close", None))
        self.action_close.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.action_export.setText(_translate("MainWindow", "Export Configuration...", None))

from pyqtgraph import GraphicsView
from .widgets import QDoubleSlider
